name = "ai-scraping-receipt"
main = "src/index.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "crawlerreceipt.com", custom_domain = true },
  { pattern = "www.crawlerreceipt.com", custom_domain = true }
]
